-- Manifest for the XReactor installer (hashes and required files).
return {
  manifest_version = 2,
  source_ref = "main",
  hash_algo = "crc32",
  installer_min_version = "1.3",
  installer_path = "xreactor/installer/installer_core.lua",
  installer_hash = "911d7886",
  installer_size_bytes = 68007,
  files = {
    { path = "xreactor/core/network.lua", size_bytes = 3241, hash = "870f6483" },
    { path = "xreactor/core/trends.lua", size_bytes = 1791, hash = "d01a6948" },
    { path = "xreactor/core/utils.lua", size_bytes = 4487, hash = "f9f8e6e5" },
    { path = "xreactor/core/logger.lua", size_bytes = 4275, hash = "de466bc4" },
    { path = "xreactor/core/ui.lua", size_bytes = 6038, hash = "1d5c8711" },
    { path = "xreactor/core/protocol.lua", size_bytes = 4869, hash = "658c5c2e" },
    { path = "xreactor/core/safety.lua", size_bytes = 771, hash = "73bab9de" },
    { path = "xreactor/core/state_machine.lua", size_bytes = 842, hash = "4ae6c19c" },
    { path = "xreactor/nodes/rt/config.lua", size_bytes = 907, hash = "1f8ef5db" },
    { path = "xreactor/nodes/rt/main.lua", size_bytes = 60401, hash = "cc318525" },
    { path = "xreactor/nodes/reprocessor/config.lua", size_bytes = 651, hash = "7835de50" },
    { path = "xreactor/nodes/reprocessor/main.lua", size_bytes = 3378, hash = "406d617c" },
    { path = "xreactor/nodes/water/config.lua", size_bytes = 755, hash = "d93b60c0" },
    { path = "xreactor/nodes/water/main.lua", size_bytes = 2802, hash = "4ef08082" },
    { path = "xreactor/nodes/fuel/config.lua", size_bytes = 740, hash = "369cad5d" },
    { path = "xreactor/nodes/fuel/main.lua", size_bytes = 3458, hash = "1c3dae39" },
    { path = "xreactor/nodes/energy/config.lua", size_bytes = 759, hash = "9c88d6f8" },
    { path = "xreactor/nodes/energy/main.lua", size_bytes = 3420, hash = "83340314" },
    { path = "xreactor/master/config.lua", size_bytes = 1329, hash = "3b58b0ad" },
    { path = "xreactor/master/startup_sequencer.lua", size_bytes = 3239, hash = "d9c315f6" },
    { path = "xreactor/master/profiles.lua", size_bytes = 164, hash = "9068a725" },
    { path = "xreactor/master/main.lua", size_bytes = 21371, hash = "60d6890d" },
    { path = "xreactor/master/ui/alarms.lua", size_bytes = 1245, hash = "ab00070b" },
    { path = "xreactor/master/ui/resources.lua", size_bytes = 2153, hash = "b53ec1e1" },
    { path = "xreactor/master/ui/rt_dashboard.lua", size_bytes = 1817, hash = "b4236ca1" },
    { path = "xreactor/master/ui/overview.lua", size_bytes = 4222, hash = "cb28b4ab" },
    { path = "xreactor/master/ui/energy.lua", size_bytes = 1365, hash = "dde1b1ae" },
    { path = "xreactor/shared/colors.lua", size_bytes = 332, hash = "445d12af" },
    { path = "xreactor/shared/constants.lua", size_bytes = 1318, hash = "10abc7ee" },
    { path = "xreactor/installer/installer.lua", size_bytes = 1149, hash = "2ce9dce3" },
    { path = "xreactor/installer/installer_core.lua", size_bytes = 68007, hash = "911d7886" },
    { path = "xreactor/installer/release.lua", size_bytes = 216, hash = "bc1c8639" }
  }
}
