local eq_cls=dofile("tests/sim/cc/event_queue.lua")
local http_m=dofile("tests/sim/cc/http.lua")
local err_m=dofile("tests/sim/cc/http_error.lua")
local function A(a,e,m) if a~=e then error((m or"eq")..": exp="..tostring(e).." act="..tostring(a)) end end
local function T(v,m) if not v then error(m or"true") end end
local eq=eq_cls.new(); local http=http_m.new(eq)
http.stub("http://ok",err_m.make_stub("success",{body="data"}))
http.request("http://ok"); http.tick()
local ev,_,h=eq:pull("http_success"); A(ev,"http_success","s"); A(h.readAll(),"data","body")
http.stub("http://err",err_m.make_stub("error",{status=500}))
http.request("http://err"); http.tick()
local ef=eq:pull(); A(ef,"http_failure","err ev")
http.stub("http://slow",err_m.make_stub("timeout"))
http.request("http://slow"); http.tick()
local et,_,tm=eq:pull(); A(et,"http_failure","to ev"); T(tostring(tm):find("timeout")~=nil,"to msg")
local h2=http.get("http://ok"); T(h2~=nil,"get ok"); A(h2.readAll(),"data","get body")
http.stub("http://corrupt",err_m.make_stub("corrupt",{body="full_body"}))
local h3=http.get("http://corrupt"); T(h3~=nil,"corrupt"); T(#h3.readAll()<#"full_body","shorter")
http.stub("http://404",err_m.make_stub("not_found"))
http.request("http://404"); http.tick()
local e5,_,m5=eq:pull(); A(e5,"http_failure","404 ev"); T(tostring(m5):find("404")~=nil,"404 msg")
print("sim_http_error_contract_test.lua: ok")
