local eq_cls=dofile("tests/sim/cc/event_queue.lua")
local modem_m=dofile("tests/sim/cc/modem.lua")
local function A(a,e,m) if a~=e then error((m or"eq")..": exp="..tostring(e).." act="..tostring(a)) end end
local function T(v,m) if not v then error(m or"true") end end
local bus=modem_m.new({profile="clean"})
local eq1=eq_cls.new(); local eq2=eq_cls.new()
local m1=bus.make_modem("a",eq1); local m2=bus.make_modem("b",eq2)
m1.open(6500); m2.open(6500)
T(m1.isOpen(6500),"open"); T(m2.isOpen(6500),"open2"); T(not m1.isOpen(9999),"not open")
m1.transmit(6500,6501,{payload="hello"})
local n=bus.tick(); A(n,1,"1msg")
local ev,side,ch,reply,msg=eq2:pull("modem_message")
A(ev,"modem_message","ev"); A(ch,6500,"ch"); A(reply,6501,"rep"); A(msg.payload,"hello","pl")
A(eq1:size(),0,"no echo")
m2.close(6500); m1.transmit(6500,6501,"x"); bus.tick(); A(eq2:size(),0,"closed")
T(not m2.isOpen(9000),"no 9000")
m1.transmit(9000,0,"y"); bus.tick(); A(eq2:size(),0,"closed 9000")
m2.open(9000); m1.transmit(9000,0,"z"); bus.tick(); A(eq2:size(),1,"open 9000"); eq2:pull()
local b2=modem_m.new({profile="drop",drop_rate=1.0,seed=42})
local ea=eq_cls.new(); local eb=eq_cls.new()
local ma=b2.make_modem("ma",ea); local mb=b2.make_modem("mb",eb)
ma.open(1); mb.open(1); ma.transmit(1,0,"d"); b2.tick(); A(eb:size(),0,"drop")
local b3=modem_m.new({profile="duplicate",dup_rate=1.0,seed=0})
local ec=eq_cls.new(); local ed=eq_cls.new()
local mc=b3.make_modem("mc",ec); local md=b3.make_modem("md",ed)
mc.open(2); md.open(2); mc.transmit(2,0,"dup"); b3.tick(); A(ed:size(),2,"dup 2")
print("sim_modem_contract_test.lua: ok")
