local health_codes = {
  NO_MONITOR = "NO_MONITOR",
  NO_MATRIX = "NO_MATRIX",
  NO_STORAGE = "NO_STORAGE",
  NO_TURBINE = "NO_TURBINE",
  NO_REACTOR = "NO_REACTOR",
  DISCOVERY_FAILED = "DISCOVERY_FAILED",
  CONTROL_DEGRADED = "CONTROL_DEGRADED",
  PROTO_MISMATCH = "PROTO_MISMATCH",
  COMMS_DOWN = "COMMS_DOWN"
}

return health_codes
