-- xreactor/manifest.lua -- manifest-v28
return {
  manifest_version = 28,
  manifest_id = "manifest-v28",
  source_ref = "beta",
  hash_algo = "crc32",

  base_files = {
  { path = "installer_http.lua", size_bytes = 1774, hash = "2d627c52", always=true },
  { path = "installer_main.lua", size_bytes = 19798, hash = "91b13c2e", always=true },
  { path = "installer_manifest.lua", size_bytes = 4673, hash = "7aa0c027", always=true },
  { path = "installer_stage.lua", size_bytes = 7475, hash = "4c136db1", always=true },
  { path = "installer_startup.lua", size_bytes = 845, hash = "6939c5e9", always=true },
  { path = "installer_storage.lua", size_bytes = 8859, hash = "89a9376e", always=true },
  { path = "release.lua", size_bytes = 345, hash = "f8af12c3", always=true },
  { path = "start.lua", size_bytes = 6323, hash = "f6b12e29", always=true },
  { path = "shared/build_info.lua", size_bytes = 1312, hash = "328286a9", always=true },
  { path = "shared/constants.lua", size_bytes = 1483, hash = "d2ed3e1d", always=true },
  { path = "adapters/monitor.lua", size_bytes = 5312, hash = "34f32460" },
  { path = "core/bootstrap.lua", size_bytes = 10909, hash = "c99887b8" },
  { path = "core/comms.lua", size_bytes = 24518, hash = "4f174212" },
  { path = "core/health.lua", size_bytes = 1918, hash = "48d5bd7f" },
  { path = "core/logger.lua", size_bytes = 30592, hash = "1688d3c8" },
  { path = "core/monitor_manager.lua", size_bytes = 7592, hash = "7bdff373" },
  { path = "core/network.lua", size_bytes = 14944, hash = "37d592dc" },
  { path = "core/non_rt_config.lua", size_bytes = 4183, hash = "6f5bf45f" },
  { path = "core/non_rt_payload.lua", size_bytes = 558, hash = "b9c0175d" },
  { path = "core/protocol.lua", size_bytes = 6423, hash = "6c324af5" },
  { path = "core/registry.lua", size_bytes = 12481, hash = "f36ffed9" },
  { path = "core/remote_log.lua", size_bytes = 4202, hash = "b1320caf" },
  { path = "core/safety.lua", size_bytes = 7851, hash = "3d0160cc" },
  { path = "core/state_machine.lua", size_bytes = 842, hash = "4ae6c19c" },
  { path = "core/time.lua", size_bytes = 454, hash = "52e5eb5d" },
  { path = "core/trends.lua", size_bytes = 1791, hash = "d01a6948" },
  { path = "core/ui.lua", size_bytes = 11243, hash = "c7d90a12" },
  { path = "core/ui_router.lua", size_bytes = 6305, hash = "e626dd67" },
  { path = "core/utils.lua", size_bytes = 19223, hash = "af1e79f6" },
  { path = "core/alerts.lua", size_bytes = 7905, hash = "976d542c" },
  { path = "services/alert_service.lua", size_bytes = 11418, hash = "d04e6700" },
  { path = "services/comms_service.lua", size_bytes = 8562, hash = "4b2957a5" },
  { path = "services/control_service.lua", size_bytes = 610, hash = "e09ee7b4" },
  { path = "services/discovery_service.lua", size_bytes = 3157, hash = "600b94de" },
  { path = "services/service_manager.lua", size_bytes = 5943, hash = "ac30751e" },
  { path = "services/telemetry_service.lua", size_bytes = 5651, hash = "1bdb3693" },
  { path = "services/ui_service.lua", size_bytes = 1624, hash = "cd6587fc" },
  { path = "shared/colors.lua", size_bytes = 332, hash = "445d12af" },
  { path = "shared/health_codes.lua", size_bytes = 336, hash = "e1d7e466" },
  { path = "shared/telemetry_schema.lua", size_bytes = 938, hash = "9567b224" },
  },

  roles = {
    master = {
    { path = "core/alert_rules.lua", size_bytes = 13600, hash = "3ef37a5e", required_for={"MASTER"} },
    { path = "master/config.lua", size_bytes = 6008, hash = "42c051e4", required_for={"MASTER"} },
    { path = "master/housekeeping.lua", size_bytes = 1952, hash = "d4ae44ae", required_for={"MASTER"} },
    { path = "master/init_runtime.lua", size_bytes = 6650, hash = "2e9ebf45", required_for={"MASTER"} },
    { path = "master/main.lua", size_bytes = 244, hash = "5f009046", required_for={"MASTER"} },
    { path = "master/message_handlers.lua", size_bytes = 19976, hash = "b051254d", required_for={"MASTER"} },
    { path = "master/monitor_sessions.lua", size_bytes = 5830, hash = "0db7c0da", required_for={"MASTER"} },
    { path = "master/profiles.lua", size_bytes = 164, hash = "9068a725", required_for={"MASTER"} },
    { path = "master/rt_sync.lua", size_bytes = 19540, hash = "18469f5b", required_for={"MASTER"} },
    { path = "master/rt_sync_coalescer.lua", size_bytes = 7700, hash = "ba3ce844", required_for={"MASTER"} },
    { path = "master/runtime_context.lua", size_bytes = 5633, hash = "5740fe39", required_for={"MASTER"} },
    { path = "master/runtime_loop.lua", size_bytes = 12291, hash = "21b324d9", required_for={"MASTER"} },
    { path = "master/runtime_ops_monitor.lua", size_bytes = 2634, hash = "8454a2a2", required_for={"MASTER"} },
    { path = "master/runtime_ops_profile.lua", size_bytes = 5068, hash = "af602146", required_for={"MASTER"} },
    { path = "master/runtime_ops_rt.lua", size_bytes = 14772, hash = "3deed5fd", required_for={"MASTER"} },
    { path = "master/startup_sequencer.lua", size_bytes = 9172, hash = "01535e76", required_for={"MASTER"} },
    { path = "master/support_status.lua", size_bytes = 1385, hash = "7e4a2f0e", required_for={"MASTER"} },
    { path = "master/ui/alarms.lua", size_bytes = 1345, hash = "0a381649", required_for={"MASTER"} },
    { path = "master/ui/alerts.lua", size_bytes = 25335, hash = "746207f8", required_for={"MASTER"} },
    { path = "master/ui/energy.lua", size_bytes = 9254, hash = "38fb057f", required_for={"MASTER"} },
    { path = "master/ui/multiview.lua", size_bytes = 5389, hash = "ced614e4", required_for={"MASTER"} },
    { path = "master/ui/overview.lua", size_bytes = 10888, hash = "20dca0c4", required_for={"MASTER"} },
    { path = "master/ui/resources.lua", size_bytes = 5634, hash = "3c3f86d2", required_for={"MASTER"} },
    { path = "master/ui/rt_dashboard.lua", size_bytes = 11303, hash = "8d5ab195", required_for={"MASTER"} },
    { path = "master/ui/widgets.lua", size_bytes = 7637, hash = "24de9664", required_for={"MASTER"} },
    { path = "master/ui_controller.lua", size_bytes = 22690, hash = "285b15c4", required_for={"MASTER"} },
    { path = "master/ui_diagnostics.lua", size_bytes = 830, hash = "d2a9d0fb", required_for={"MASTER"} },
    },
    rt = {
    { path = "adapters/reactor.lua", size_bytes = 18666, hash = "ae0b468e", required_for={"RT"} },
    { path = "adapters/turbine.lua", size_bytes = 3871, hash = "a9e924f3", required_for={"RT"} },
    { path = "core/control_rails.lua", size_bytes = 8017, hash = "01c1a770", required_for={"RT"} },
    { path = "core/fluid.lua", size_bytes = 5017, hash = "9a5c0bea", required_for={"RT"} },
    { path = "core/turbine_ctrl.lua", size_bytes = 2988, hash = "afe549dc", required_for={"RT"} },
    { path = "core/turbine_regulator.lua", size_bytes = 16601, hash = "7e2685eb", required_for={"RT"} },
    { path = "nodes/rt/binding.lua", size_bytes = 3470, hash = "0406bc48", required_for={"RT"} },
    { path = "nodes/rt/command_handler.lua", size_bytes = 10505, hash = "f10ddd24", required_for={"RT"} },
    { path = "nodes/rt/config.lua", size_bytes = 3065, hash = "3f63dd70", required_for={"RT"} },
    { path = "nodes/rt/config_normalizer.lua", size_bytes = 23479, hash = "e924f652", required_for={"RT"} },
    { path = "nodes/rt/discovery_log.lua", size_bytes = 1080, hash = "7d9ceb62", required_for={"RT"} },
    { path = "nodes/rt/discovery_runtime.lua", size_bytes = 9137, hash = "31ad3d94", required_for={"RT"} },
    { path = "nodes/rt/flow_apply_helpers.lua", size_bytes = 10399, hash = "50d81d1a", required_for={"RT"} },
    { path = "nodes/rt/health_payload.lua", size_bytes = 2723, hash = "7a3f83b2", required_for={"RT"} },
    { path = "nodes/rt/main.lua", size_bytes = 85143, hash = "77feef14", required_for={"RT"} },
    { path = "nodes/rt/module_lifecycle.lua", size_bytes = 26972, hash = "f7b7c4c2", required_for={"RT"} },
    { path = "nodes/rt/monitor_ui.lua", size_bytes = 20646, hash = "ea107a45", required_for={"RT"} },
    { path = "nodes/rt/reactor_steam_guard.lua", size_bytes = 2613, hash = "2f2fa78c", required_for={"RT"} },
    { path = "nodes/rt/startup_diagnostics.lua", size_bytes = 2525, hash = "3e823eea", required_for={"RT"} },
    { path = "nodes/rt/state_handlers.lua", size_bytes = 8485, hash = "6c8b12e2", required_for={"RT"} },
    { path = "nodes/rt/status_snapshot.lua", size_bytes = 8996, hash = "b64b147e", required_for={"RT"} },
    },
    energy = {
    { path = "adapters/energy_storage.lua", size_bytes = 3648, hash = "fd2dc2e5", required_for={"ENERGY"} },
    { path = "adapters/induction_matrix.lua", size_bytes = 15124, hash = "c3006e4d", required_for={"ENERGY"} },
    { path = "services/matrix_sampling_service.lua", size_bytes = 867, hash = "fff32232", required_for={"ENERGY"} },
    { path = "nodes/energy/command_handler.lua", size_bytes = 1888, hash = "0e87a567", required_for={"ENERGY"} },
    { path = "nodes/energy/config.lua", size_bytes = 7214, hash = "3b0917b4", required_for={"ENERGY"} },
    { path = "nodes/energy/config_normalizer.lua", size_bytes = 11646, hash = "cf7b3c16", required_for={"ENERGY"} },
    { path = "nodes/energy/discovery_log.lua", size_bytes = 2433, hash = "4f723e27", required_for={"ENERGY"} },
    { path = "nodes/energy/discovery_runtime.lua", size_bytes = 16744, hash = "8c0880a2", required_for={"ENERGY"} },
    { path = "nodes/energy/main.lua", size_bytes = 23024, hash = "96ae483f", required_for={"ENERGY"} },
    { path = "nodes/energy/matrix_snapshot_runtime.lua", size_bytes = 17828, hash = "aa3e0e6d", required_for={"ENERGY"} },
    { path = "nodes/energy/matrix_topology_cache.lua", size_bytes = 2052, hash = "54dc9081", required_for={"ENERGY"} },
    { path = "nodes/energy/runtime_context.lua", size_bytes = 1914, hash = "447ea770", required_for={"ENERGY"} },
    { path = "nodes/energy/status_payload.lua", size_bytes = 8113, hash = "8f3f1ca0", required_for={"ENERGY"} },
    { path = "nodes/energy/storage_snapshot_runtime.lua", size_bytes = 3311, hash = "5a14cbff", required_for={"ENERGY"} },
    { path = "nodes/energy/ui_model.lua", size_bytes = 6005, hash = "faa185db", required_for={"ENERGY"} },
    { path = "nodes/energy/ui_pages.lua", size_bytes = 7659, hash = "9be1390d", required_for={"ENERGY"} },
    },
    water = {
    { path = "nodes/water/config.lua", size_bytes = 3793, hash = "3b282920", required_for={"WATER"} },
    { path = "nodes/water/config_normalizer.lua", size_bytes = 989, hash = "09141fba", required_for={"WATER"} },
    { path = "nodes/water/main.lua", size_bytes = 17271, hash = "9df06de8", required_for={"WATER"} },
    { path = "nodes/water/role_descriptor.lua", size_bytes = 152, hash = "c76ee5e7", required_for={"WATER"} },
    },
    fuel = {
    { path = "nodes/fuel/config.lua", size_bytes = 5156, hash = "f798aaf6", required_for={"FUEL"} },
    { path = "nodes/fuel/config_normalizer.lua", size_bytes = 2946, hash = "b3be18dd", required_for={"FUEL"} },
    { path = "nodes/fuel/main.lua", size_bytes = 17152, hash = "387cee5e", required_for={"FUEL"} },
    { path = "nodes/fuel/role_descriptor.lua", size_bytes = 147, hash = "1b38a051", required_for={"FUEL"} },
    },
    reprocessing = {
    { path = "nodes/reprocessor/config.lua", size_bytes = 4708, hash = "febd3cce", required_for={"REPROCESSING"} },
    { path = "nodes/reprocessor/config_normalizer.lua", size_bytes = 2075, hash = "79f115bc", required_for={"REPROCESSING"} },
    { path = "nodes/reprocessor/main.lua", size_bytes = 17352, hash = "385f9350", required_for={"REPROCESSING"} },
    { path = "nodes/reprocessor/role_descriptor.lua", size_bytes = 177, hash = "3a1d8dc9", required_for={"REPROCESSING"} },
    },
    log = {
    { path = "nodes/log_collector/main.lua", size_bytes = 26320, hash = "6c657de3", required_for={"LOG"} },
    },
    shared_support = {
    { path = "nodes/support/command_handler.lua", size_bytes = 4590, hash = "568a2b45", required_for={"WATER", "FUEL", "REPROCESSING"} },
    { path = "nodes/support/discovery.lua", size_bytes = 1343, hash = "e8aa30c3", required_for={"WATER", "FUEL", "REPROCESSING"} },
    { path = "nodes/support/role_logic.lua", size_bytes = 571, hash = "a3d15a39", required_for={"ENERGY", "WATER", "FUEL", "REPROCESSING"} },
    { path = "nodes/support/runtime.lua", size_bytes = 2656, hash = "0f4d68a2", required_for={"WATER", "FUEL", "REPROCESSING"} },
    { path = "nodes/support/ui_pages.lua", size_bytes = 3388, hash = "71cd674e", required_for={"WATER", "FUEL", "REPROCESSING"} },
    },
  },

  dev_files = {},
}
