-- xreactor/manifest.lua
return {
  manifest_version = 598,
  manifest_id = "manifest-v598",
  source_ref = "beta",
  hash_algo = "crc32",

  base_files = {
  { path = "installer/http.lua", size_bytes = 4112, hash = "25ddced5", always = true },
  { path = "installer/manifest.lua", size_bytes = 6436, hash = "e18844b4", always = true },
  { path = "installer/stage.lua", size_bytes = 9132, hash = "b87557db", always = true },
  { path = "installer/ui.lua", size_bytes = 1971, hash = "02e204ae", always = true },
  { path = "installer/auto_update.lua", size_bytes = 17000, hash = "da923510", always = true },
  { path = "installer/init.lua", size_bytes = 22827, hash = "20dd5066", always = true },
  { path = "installer/reactor_naming.lua", size_bytes = 13072, hash = "dc01bce2", always = true },
  { path = "installer/journal.lua", size_bytes = 8650, hash = "18811651", always = true },
  { path = "installer/plan_validator.lua", size_bytes = 5738, hash = "8c854740", always = true },
  { path = "release.lua", size_bytes = 345, hash = "2a61f68e", always = true },
  { path = "start.lua", size_bytes = 14309, hash = "b45f3f06", always = true },
  { path = "shared/build_info.lua", size_bytes = 1312, hash = "328286a9", always = true },
  { path = "shared/constants.lua", size_bytes = 2963, hash = "d5ed0967", always = true },
  { path = "core/mockup_ui.lua", size_bytes = 10004, hash = "94f3bfb5", always = true },
  { path = "adapters/monitor.lua", size_bytes = 7953, hash = "a3b79bd4", required_for={"MASTER","RT","ENERGY","WATER","FUEL","REPROCESSING"} },
  { path = "core/bootstrap.lua", size_bytes = 11202, hash = "e54f2a38", always = true },
  { path = "core/update_handshake.lua", size_bytes = 4701, hash = "94353b43", always = true },
  { path = "core/comms.lua", size_bytes = 26298, hash = "5b58cee3" },
  { path = "core/health.lua", size_bytes = 1918, hash = "48d5bd7f" },
  { path = "core/logger.lua", size_bytes = 31349, hash = "7c76bc52" },
  { path = "core/monitor_manager.lua", size_bytes = 9919, hash = "3f982d0b", required_for={"MASTER"} },
  { path = "core/network.lua", size_bytes = 15457, hash = "732d98cc" },
  { path = "core/non_rt_config.lua", size_bytes = 4183, hash = "6f5bf45f", required_for={"WATER","FUEL","REPROCESSING"} },
  { path = "core/non_rt_payload.lua", size_bytes = 558, hash = "b9c0175d", required_for={"VALVE","WATER","FUEL","REPROCESSING"} },
  { path = "core/protocol.lua", size_bytes = 7370, hash = "4564c676" },
  { path = "core/reactor_identity.lua", size_bytes = 1610, hash = "059a6785", required_for={"MASTER","RT","FUEL"} },
  { path = "core/registry.lua", size_bytes = 12798, hash = "dfee2f71", required_for={"MASTER","RT","ENERGY","WATER","FUEL","REPROCESSING"} },
  { path = "core/safety.lua", size_bytes = 7851, hash = "3d0160cc", required_for={"MASTER","RT","FUEL"} },
  { path = "core/state_machine.lua", size_bytes = 842, hash = "4ae6c19c", required_for={"RT"} },
  { path = "core/startup_report.lua", size_bytes = 3845, hash = "d817d5e3", always = true },
  { path = "core/time.lua", size_bytes = 454, hash = "52e5eb5d", required_for={"MASTER"} },
  { path = "core/trends.lua", size_bytes = 1791, hash = "d01a6948", required_for={"MASTER"} },
  { path = "core/ui.lua", size_bytes = 12977, hash = "b0274c0e", required_for={"MASTER","RT","ENERGY","WATER","FUEL","REPROCESSING"} },
  { path = "core/ui_router.lua", size_bytes = 17445, hash = "f9e51f26", required_for={"RT","ENERGY","WATER","FUEL","REPROCESSING"} },
  { path = "core/window_buffer.lua", size_bytes = 3681, hash = "1743677d", required_for={"RT","ENERGY","WATER","FUEL","REPROCESSING"} },
  { path = "core/utils.lua", size_bytes = 24296, hash = "f9cf839e" },
  { path = "core/remote_update.lua", size_bytes = 4347, hash = "13acf7b4" },
  { path = "core/alerts.lua", size_bytes = 11106, hash = "7ca6c61c", required_for={"MASTER"} },
  -- required_for={"MASTER"}: nur master/runtime_loop.lua require()t
  -- diese Datei tatsaechlich (siehe auch core/alert_rules.lua, ihre
  -- Abhaengigkeit, ebenso auf MASTER beschraenkt).
  { path = "services/alert_service.lua", size_bytes = 14539, hash = "bdabdcb1", required_for={"MASTER"} },
  { path = "services/comms_service.lua", size_bytes = 11948, hash = "e822a614" },
  { path = "services/control_service.lua", size_bytes = 610, hash = "e09ee7b4", required_for={"MASTER"} },
  { path = "services/discovery_service.lua", size_bytes = 3157, hash = "600b94de", required_for={"RT","ENERGY","WATER","FUEL","REPROCESSING"} },
  { path = "services/service_manager.lua", size_bytes = 6565, hash = "fa13ae27" },
  { path = "services/telemetry_service.lua", size_bytes = 5651, hash = "1bdb3693" },
  { path = "services/ui_service.lua", size_bytes = 4071, hash = "5ffe2f33" },
  -- always=true: core/mockup_ui.lua (auch bei LOG_COLLECTOR installiert)
  -- require()t shared.colors unbedingt beim Laden.
  { path = "shared/colors.lua", size_bytes = 593, hash = "89e36ece", always = true },
  { path = "shared/health_codes.lua", size_bytes = 336, hash = "e1d7e466" },
  { path = "shared/telemetry_schema.lua", size_bytes = 938, hash = "9567b224" },
  },

  roles = {
    master = {
    { path = "master/config_edits.lua", size_bytes = 8693, hash = "f6e43664", required_for={"MASTER"} },
    { path = "master/context.lua", size_bytes = 5370, hash = "7e42349c", required_for={"MASTER"} },
    { path = "master/loop.lua", size_bytes = 4318, hash = "2b30d64b", required_for={"MASTER"} },
    { path = "core/alert_rules.lua", size_bytes = 17159, hash = "f436f415", required_for={"MASTER"} },
    { path = "master/config.lua", size_bytes = 6441, hash = "eee9169b", required_for={"MASTER"} },
    { path = "master/housekeeping.lua", size_bytes = 4106, hash = "c43799c5", required_for={"MASTER"} },
    { path = "master/fuel_relay.lua", size_bytes = 3413, hash = "0b9f8c37", required_for={"MASTER"} },
    { path = "master/init_runtime.lua", size_bytes = 8295, hash = "50e5b461", required_for={"MASTER"} },
    { path = "master/main.lua", size_bytes = 244, hash = "227a851a", required_for={"MASTER"} },
    { path = "master/message_handlers.lua", size_bytes = 28117, hash = "698fabfe", required_for={"MASTER"} },
    { path = "master/monitor_sessions.lua", size_bytes = 9123, hash = "69418ffa", required_for={"MASTER"} },
    { path = "master/profiles.lua", size_bytes = 275, hash = "59bdc157", required_for={"MASTER"} },
    { path = "master/rt_sync.lua", size_bytes = 18531, hash = "0df418bc", required_for={"MASTER"} },
    { path = "master/rt_sync_coalescer.lua", size_bytes = 7676, hash = "9519c601", required_for={"MASTER"} },
    { path = "master/runtime_loop.lua", size_bytes = 16707, hash = "74936714", required_for={"MASTER"} },
    { path = "master/runtime_ops_monitor.lua", size_bytes = 2634, hash = "8454a2a2", required_for={"MASTER"} },
    { path = "master/runtime_ops_profile.lua", size_bytes = 8994, hash = "1017c3d3", required_for={"MASTER"} },
    { path = "master/runtime_ops_rt.lua", size_bytes = 16692, hash = "45ba275f", required_for={"MASTER"} },
    { path = "master/startup_sequencer.lua", size_bytes = 11394, hash = "d90e5035", required_for={"MASTER"} },
    { path = "master/support_status.lua", size_bytes = 1385, hash = "7e4a2f0e", required_for={"MASTER"} },
    { path = "master/ui/alarms.lua", size_bytes = 7730, hash = "50e520ed", required_for={"MASTER"} },
    { path = "master/ui/alerts.lua", size_bytes = 28137, hash = "4bf57a50", required_for={"MASTER"} },
    { path = "master/ui/energy.lua", size_bytes = 9254, hash = "38fb057f", required_for={"MASTER"} },
    { path = "master/ui/multiview.lua", size_bytes = 16482, hash = "7e1c435e", required_for={"MASTER"} },
    { path = "master/ui/overview.lua", size_bytes = 13792, hash = "33054a4f", required_for={"MASTER"} },
    { path = "master/ui/resources.lua", size_bytes = 6869, hash = "a28f683a", required_for={"MASTER"} },
    { path = "master/ui/rt_dashboard.lua", size_bytes = 13157, hash = "391c3c5e", required_for={"MASTER"} },
    { path = "master/ui/widgets.lua", size_bytes = 7637, hash = "24de9664", required_for={"MASTER"} },
    { path = "master/ui/layout.lua", size_bytes = 5981, hash = "bbec1760", required_for={"MASTER"} },
    { path = "master/ui/maintenance.lua", size_bytes = 4360, hash = "17833cc1", required_for={"MASTER"} },
    { path = "master/ui/updates.lua", size_bytes = 4768, hash = "60c2f1b0", required_for={"MASTER"} },
    { path = "master/ui/system_map.lua", size_bytes = 5870, hash = "8c265931", required_for={"MASTER"} },
    { path = "master/ui/config_editor.lua", size_bytes = 6111, hash = "8d0407ad", required_for={"MASTER"} },
    -- VALVE bewusst nicht in required_for: hat einen eigenen, fest
    -- eingebauten 1x1-Statusmonitor in nodes/valve/main.lua
    -- (render_status_monitor()), unabhaengig von diesem 1x3-Ampel-Modul.
    { path = "optional/ampel.lua", size_bytes = 5398, hash = "e02e967f", optional=true, feature="ampel", required_for={"RT","ENERGY","WATER","FUEL","REPROCESSING","LOG"} },
    -- required_for entspricht den tatsaechlichen
    -- require("optional.speaker_alarm")-Aufrufstellen (alle Node-main.lua
    -- ausser VALVE, plus services/alert_service.lua/MASTER); anders als
    -- "ampel" (eigenes "master_ampel"-Feature) gibt es fuer speaker_alarm
    -- keine getrennte MASTER-Variante.
    { path = "optional/speaker_alarm.lua", size_bytes = 5221, hash = "a0c7b007", optional=true, feature="speaker_alarm", required_for={"RT","ENERGY","WATER","FUEL","REPROCESSING","LOG","MASTER"} },
    { path = "optional/pocket_query_handler.lua", size_bytes = 5751, hash = "4b81ecb2", optional=true, feature="pocket_query", required_for={"MASTER"} },
    -- Manual install only: Pocket Computer ist kein waehlbarer Rollen-Typ
    -- im Installer. optional=true + leeres required_for={} sorgt dafuer,
    -- dass es weder automatisch installiert noch als Auswahl-Prompt bei
    -- irgendeiner Rolle auftaucht; trotzdem im Manifest gefuehrt, damit
    -- Groesse/Hash bei gezieltem manuellem Download verifizierbar sind.
    { path = "optional/pocket_client.lua", size_bytes = 10477, hash = "bf1a75b4", optional=true, feature="pocket_client", required_for={} },
    { path = "optional/master_ampel.lua", size_bytes = 5891, hash = "13753910", optional=true, feature="master_ampel", required_for={"MASTER"} },
    { path = "master/ui_controller.lua", size_bytes = 50427, hash = "f85633c4", required_for={"MASTER"} },
    { path = "master/ui_diagnostics.lua", size_bytes = 830, hash = "d2a9d0fb", required_for={"MASTER"} },
    },
    rt = {
    { path = "adapters/reactor.lua", size_bytes = 18944, hash = "17252797", required_for={"RT"} },
    { path = "adapters/turbine.lua", size_bytes = 3871, hash = "a9e924f3", required_for={"RT"} },
    { path = "core/control_rails.lua", size_bytes = 8017, hash = "01c1a770", required_for={"RT"} },
    { path = "core/fluid.lua", size_bytes = 5017, hash = "9a5c0bea", required_for={"RT"} },
    { path = "core/turbine_regulator.lua", size_bytes = 13632, hash = "7001b6cc", required_for={"RT"} },
    { path = "nodes/rt/binding.lua", size_bytes = 3507, hash = "87255444", required_for={"RT"} },
    { path = "nodes/rt/command_handler.lua", size_bytes = 10464, hash = "e2509d86", required_for={"RT"} },
    { path = "nodes/rt/reactor_control.lua", size_bytes = 37196, hash = "fc6df8cf", required_for={"RT"} },
    { path = "nodes/rt/turbine_control.lua", size_bytes = 41806, hash = "c9c9fdde", required_for={"RT"} },
    { path = "nodes/rt/capacity_learning.lua", size_bytes = 3907, hash = "4f56566d", required_for={"RT"} },
    { path = "nodes/rt/capacity_cache.lua", size_bytes = 1556, hash = "86f9a268", required_for={"RT"} },
    { path = "nodes/rt/config.lua", size_bytes = 5433, hash = "db255dd7", required_for={"RT"} },
    { path = "nodes/rt/config_normalizer.lua", size_bytes = 27603, hash = "1706b2db", required_for={"RT"} },
    { path = "nodes/rt/discovery_log.lua", size_bytes = 1080, hash = "7d9ceb62", required_for={"RT"} },
    { path = "nodes/rt/discovery_runtime.lua", size_bytes = 12388, hash = "1594b2fc", required_for={"RT"} },
    { path = "nodes/rt/flow_apply_helpers.lua", size_bytes = 4274, hash = "ee801517", required_for={"RT"} },
    { path = "nodes/rt/health_payload.lua", size_bytes = 2723, hash = "7a3f83b2", required_for={"RT"} },
    { path = "nodes/rt/main.lua", size_bytes = 47730, hash = "d5f46b04", required_for={"RT"} },
    { path = "nodes/rt/module_lifecycle.lua", size_bytes = 29930, hash = "62554c06", required_for={"RT"} },
    { path = "nodes/rt/monitor_ui.lua", size_bytes = 15073, hash = "033d7f12", required_for={"RT"} },
    { path = "nodes/rt/mockup_pages.lua", size_bytes = 16815, hash = "a497111e", required_for={"RT"} },
    { path = "nodes/rt/reactor_steam_guard.lua", size_bytes = 2613, hash = "2f2fa78c", required_for={"RT"} },
    { path = "nodes/rt/startup_diagnostics.lua", size_bytes = 2613, hash = "e5d63978", required_for={"RT"} },
    { path = "nodes/rt/state_handlers.lua", size_bytes = 9257, hash = "bb391437", required_for={"RT"} },
    { path = "nodes/rt/status_snapshot.lua", size_bytes = 6415, hash = "26a67eb2", required_for={"RT"} },
    },
    energy = {
    { path = "nodes/energy/heartbeat.lua", size_bytes = 5131, hash = "84035306", required_for={"ENERGY"} },
    { path = "nodes/energy/matrix.lua", size_bytes = 1672, hash = "6b957631", required_for={"ENERGY"} },
    { path = "adapters/energy_storage.lua", size_bytes = 4023, hash = "444e8082", required_for={"ENERGY"} },
    { path = "adapters/induction_matrix.lua", size_bytes = 15124, hash = "c3006e4d", required_for={"ENERGY"} },
    { path = "services/matrix_sampling_service.lua", size_bytes = 867, hash = "fff32232", required_for={"ENERGY"} },
    { path = "nodes/energy/command_handler.lua", size_bytes = 1329, hash = "e6b074ac", required_for={"ENERGY"} },
    { path = "nodes/energy/config.lua", size_bytes = 6023, hash = "d84742e5", required_for={"ENERGY"} },
    { path = "nodes/energy/config_normalizer.lua", size_bytes = 6392, hash = "0452f64d", required_for={"ENERGY"} },
    { path = "nodes/energy/discovery_log.lua", size_bytes = 2433, hash = "4f723e27", required_for={"ENERGY"} },
    { path = "nodes/energy/discovery_runtime.lua", size_bytes = 17168, hash = "4d225311", required_for={"ENERGY"} },
    { path = "nodes/energy/main.lua", size_bytes = 21930, hash = "b5f3b9be", required_for={"ENERGY"} },
    { path = "nodes/energy/matrix_snapshot_runtime.lua", size_bytes = 17084, hash = "e1dc1663", required_for={"ENERGY"} },
    { path = "nodes/energy/matrix_topology_cache.lua", size_bytes = 1848, hash = "577d235b", required_for={"ENERGY"} },
    { path = "nodes/energy/runtime_context.lua", size_bytes = 1928, hash = "f9d9a168", required_for={"ENERGY"} },
    { path = "nodes/energy/status_payload.lua", size_bytes = 9098, hash = "f01b2d8b", required_for={"ENERGY"} },
    { path = "nodes/energy/storage_snapshot_runtime.lua", size_bytes = 6118, hash = "04b90706", required_for={"ENERGY"} },
    { path = "nodes/energy/ui_model.lua", size_bytes = 4152, hash = "e44f676b", required_for={"ENERGY"} },
    { path = "nodes/energy/ui_pages.lua", size_bytes = 19004, hash = "4720b411", required_for={"ENERGY"} },
    },
    water = {
    { path = "nodes/water/config.lua", size_bytes = 3884, hash = "1804d0e7", required_for={"WATER"} },
    { path = "nodes/water/config_normalizer.lua", size_bytes = 2642, hash = "f7ad6214", required_for={"WATER"} },
    { path = "nodes/water/main.lua", size_bytes = 25214, hash = "cc3ee93b", required_for={"WATER"} },
    { path = "nodes/water/ui_pages.lua", size_bytes = 10862, hash = "cfbbd586", required_for={"WATER"} },
    { path = "nodes/water/role_descriptor.lua", size_bytes = 152, hash = "c76ee5e7", required_for={"WATER"} },
    },
    fuel = {
    { path = "nodes/fuel/config.lua", size_bytes = 7188, hash = "1a2722a9", required_for={"FUEL"} },
    { path = "nodes/fuel/config_normalizer.lua", size_bytes = 6065, hash = "8eaa6398", required_for={"FUEL"} },
    { path = "nodes/fuel/main.lua", size_bytes = 19764, hash = "b20b6657", required_for={"FUEL"} },
    { path = "nodes/fuel/status_snapshot.lua", size_bytes = 4662, hash = "cc71fd01", required_for={"FUEL"} },
    { path = "nodes/fuel/operational_summary.lua", size_bytes = 7915, hash = "0e2fd9d7", required_for={"FUEL"} },
    { path = "nodes/fuel/command_handler.lua", size_bytes = 2032, hash = "dac721b1", required_for={"FUEL"} },
    { path = "nodes/fuel/fuel_status_network.lua", size_bytes = 7855, hash = "53d04318", required_for={"FUEL"} },
    { path = "nodes/fuel/reactor_targets.lua", size_bytes = 1815, hash = "17439bad", required_for={"FUEL"} },
    { path = "nodes/fuel/monitor_ui.lua", size_bytes = 7945, hash = "2759ef51", required_for={"FUEL"} },
    { path = "nodes/fuel/ui_completion.lua", size_bytes = 17973, hash = "fba02cac", required_for={"FUEL"} },
    { path = "nodes/fuel/storage.lua", size_bytes = 2167, hash = "a33a6a45", required_for={"FUEL"} },
    { path = "nodes/fuel/ui_pages.lua", size_bytes = 6466, hash = "1898ddc4", required_for={"FUEL"} },
    { path = "nodes/fuel/role_descriptor.lua", size_bytes = 147, hash = "1b38a051", required_for={"FUEL"} },
    { path = "nodes/fuel/logistics_router.lua", size_bytes = 29184, hash = "7d70bcc1", required_for={"FUEL"} },
    { path = "nodes/fuel/redstone_router.lua", size_bytes = 48683, hash = "12bdbf84", required_for={"FUEL","REPROCESSING"} },
    { path = "nodes/fuel/router_ui.lua", size_bytes = 36446, hash = "ceba2595", required_for={"FUEL","REPROCESSING"} },
    },
    reprocessing = {
    { path = "nodes/reprocessor/config.lua", size_bytes = 3626, hash = "5b906b83", required_for={"REPROCESSING"} },
    { path = "nodes/reprocessor/config_normalizer.lua", size_bytes = 2097, hash = "7b4dd612", required_for={"REPROCESSING"} },
    { path = "nodes/reprocessor/feed_router.lua", size_bytes = 9492, hash = "7ed963f3", required_for={"REPROCESSING"} },
    { path = "nodes/reprocessor/main.lua", size_bytes = 27126, hash = "8698acc1", required_for={"REPROCESSING"} },
    { path = "nodes/reprocessor/ui_pages.lua", size_bytes = 11485, hash = "40f047a9", required_for={"REPROCESSING"} },
    { path = "nodes/reprocessor/role_descriptor.lua", size_bytes = 177, hash = "3a1d8dc9", required_for={"REPROCESSING"} },
    { path = "nodes/valve/role_descriptor.lua", size_bytes = 152, hash = "aca06242", required_for={"VALVE"} },
    { path = "nodes/valve/config.lua", size_bytes = 1597, hash = "27de8d69", required_for={"VALVE"} },
    { path = "nodes/valve/controller.lua", size_bytes = 12021, hash = "992adf05", required_for={"VALVE"} },
    { path = "nodes/valve/main.lua", size_bytes = 9036, hash = "5da83e2f", required_for={"VALVE"} },
    },
    log = {
    { path = "nodes/log_collector/main.lua", size_bytes = 52245, hash = "ebd2b2db", required_for={"LOG"} },
    { path = "nodes/log_collector/mockup_main.lua", size_bytes = 1143, hash = "50fcd8e4", required_for={"LOG"} },
    { path = "nodes/log_collector/mockup_ui.lua", size_bytes = 6190, hash = "75b0732e", required_for={"LOG"} },
    { path = "nodes/log_collector/default_ui.lua", size_bytes = 4481, hash = "adeb5fa4", required_for={"LOG"} },
    },
    shared_support = {
    { path = "nodes/support/command_handler.lua", size_bytes = 4134, hash = "dbb9d0c1", required_for={"WATER", "FUEL", "REPROCESSING"} },
    { path = "nodes/support/discovery.lua", size_bytes = 1343, hash = "e8aa30c3", required_for={"WATER", "FUEL", "REPROCESSING"} },
    { path = "nodes/support/role_logic.lua", size_bytes = 571, hash = "a3d15a39", required_for={"ENERGY", "WATER", "FUEL", "REPROCESSING", "RT"} },
    { path = "nodes/support/runtime.lua", size_bytes = 8287, hash = "ffee27f4", required_for={"WATER", "FUEL", "REPROCESSING", "RT", "ENERGY", "MASTER", "VALVE"} },
    { path = "nodes/support/ui_pages.lua", size_bytes = 5590, hash = "0f675170", required_for={"WATER", "FUEL", "REPROCESSING", "ENERGY", "RT"} },
    },
  },

  dev_files = {},
}
