-- xreactor/manifest.lua -- manifest-v45
return {
  manifest_version = 71,
  manifest_id = "manifest-v71",
  source_ref = "beta",
  hash_algo = "crc32",

  base_files = {
  { path = "installer_http.lua", size_bytes = 4688, hash = "ea6f7420", always=true},
  { path = "installer_main.lua", size_bytes = 21824, hash = "db0ddafa", always=true},
  { path = "installer_manifest.lua", size_bytes = 4673, hash = "7aa0c027", always=true},
  { path = "installer_stage.lua", size_bytes = 7475, hash = "4c136db1", always=true},
  { path = "installer_startup.lua", size_bytes = 845, hash = "6939c5e9", always=true},
  { path = "installer_storage.lua", size_bytes = 8859, hash = "89a9376e", always=true},
  { path = "release.lua", size_bytes = 345, hash = "ead94571", always=true},
  { path = "start.lua", size_bytes = 6846, hash = "4c052210", always=true},
  { path = "shared/build_info.lua", size_bytes = 1312, hash = "328286a9", always=true},
  { path = "shared/constants.lua", size_bytes = 1705, hash = "4266e055", always=true},
  { path = "adapters/monitor.lua", size_bytes = 5312, hash = "34f32460"},
  { path = "core/bootstrap.lua", size_bytes = 11202, hash = "e54f2a38"},
  { path = "core/comms.lua", size_bytes = 24518, hash = "4f174212"},
  { path = "core/health.lua", size_bytes = 1918, hash = "48d5bd7f"},
  { path = "core/logger.lua", size_bytes = 31297, hash = "35081950"},
  { path = "core/monitor_manager.lua", size_bytes = 7592, hash = "7bdff373"},
  { path = "core/network.lua", size_bytes = 15309, hash = "7504d3dd"},
  { path = "core/non_rt_config.lua", size_bytes = 4183, hash = "6f5bf45f"},
  { path = "core/non_rt_payload.lua", size_bytes = 558, hash = "b9c0175d"},
  { path = "core/protocol.lua", size_bytes = 6423, hash = "6c324af5"},
  { path = "core/registry.lua", size_bytes = 12481, hash = "f36ffed9"},
  { path = "core/remote_log.lua", size_bytes = 4202, hash = "b1320caf"},
  { path = "core/safety.lua", size_bytes = 7851, hash = "3d0160cc"},
  { path = "core/state_machine.lua", size_bytes = 842, hash = "4ae6c19c"},
  { path = "core/time.lua", size_bytes = 454, hash = "52e5eb5d"},
  { path = "core/trends.lua", size_bytes = 1791, hash = "d01a6948"},
  { path = "core/ui.lua", size_bytes = 12875, hash = "2b78f4f8"},
  { path = "core/ui_router.lua", size_bytes = 6305, hash = "e626dd67"},
  { path = "core/utils.lua", size_bytes = 22758, hash = "6b637f02"},
  { path = "core/alerts.lua", size_bytes = 7905, hash = "976d542c"},
  { path = "services/alert_service.lua", size_bytes = 11418, hash = "d04e6700"},
  { path = "services/comms_service.lua", size_bytes = 8562, hash = "4b2957a5"},
  { path = "services/control_service.lua", size_bytes = 610, hash = "e09ee7b4"},
  { path = "services/discovery_service.lua", size_bytes = 3157, hash = "600b94de"},
  { path = "services/service_manager.lua", size_bytes = 5943, hash = "ac30751e"},
  { path = "services/telemetry_service.lua", size_bytes = 5651, hash = "1bdb3693"},
  { path = "services/ui_service.lua", size_bytes = 1624, hash = "cd6587fc"},
  { path = "shared/colors.lua", size_bytes = 332, hash = "445d12af"},
  { path = "shared/health_codes.lua", size_bytes = 336, hash = "e1d7e466"},
  { path = "shared/telemetry_schema.lua", size_bytes = 938, hash = "9567b224"},
  },

  roles = {
    master = {
    { path = "core/alert_rules.lua", size_bytes = 13600, hash = "3ef37a5e", required_for={"MASTER"}},
    { path = "master/config.lua", size_bytes = 6221, hash = "6dac4f39", required_for={"MASTER"}},
    { path = "master/housekeeping.lua", size_bytes = 2801, hash = "ffbc176f", required_for={"MASTER"}},
    { path = "master/init_runtime.lua", size_bytes = 7307, hash = "eba62959", required_for={"MASTER"}},
    { path = "master/main.lua", size_bytes = 244, hash = "5f009046", required_for={"MASTER"}},
    { path = "master/message_handlers.lua", size_bytes = 19707, hash = "53d2e5cb", required_for={"MASTER"}},
    { path = "master/monitor_sessions.lua", size_bytes = 5830, hash = "0db7c0da", required_for={"MASTER"}},
    { path = "master/profiles.lua", size_bytes = 164, hash = "9068a725", required_for={"MASTER"}},
    { path = "master/rt_sync.lua", size_bytes = 20616, hash = "467065d1", required_for={"MASTER"}},
    { path = "master/rt_sync_coalescer.lua", size_bytes = 7676, hash = "9519c601", required_for={"MASTER"}},
    { path = "master/runtime_context.lua", size_bytes = 5759, hash = "d0871d98", required_for={"MASTER"}},
    { path = "master/runtime_loop.lua", size_bytes = 13608, hash = "2fd580a1", required_for={"MASTER"}},
    { path = "master/runtime_ops_monitor.lua", size_bytes = 2634, hash = "8454a2a2", required_for={"MASTER"}},
    { path = "master/runtime_ops_profile.lua", size_bytes = 5173, hash = "64733c05", required_for={"MASTER"}},
    { path = "master/runtime_ops_rt.lua", size_bytes = 16286, hash = "cc9b1b4d", required_for={"MASTER"}},
    { path = "master/startup_sequencer.lua", size_bytes = 10624, hash = "4257d7fa", required_for={"MASTER"}},
    { path = "master/support_status.lua", size_bytes = 1385, hash = "7e4a2f0e", required_for={"MASTER"}},
    { path = "master/ui/alarms.lua", size_bytes = 1827, hash = "9b9ff1af", required_for={"MASTER"}},
    { path = "master/ui/alerts.lua", size_bytes = 25335, hash = "746207f8", required_for={"MASTER"}},
    { path = "master/ui/energy.lua", size_bytes = 9254, hash = "38fb057f", required_for={"MASTER"}},
    { path = "master/ui/multiview.lua", size_bytes = 5389, hash = "ced614e4", required_for={"MASTER"}},
    { path = "master/ui/overview.lua", size_bytes = 10888, hash = "20dca0c4", required_for={"MASTER"}},
    { path = "master/ui/resources.lua", size_bytes = 5634, hash = "3c3f86d2", required_for={"MASTER"}},
    { path = "master/ui/rt_dashboard.lua", size_bytes = 11303, hash = "8d5ab195", required_for={"MASTER"}},
    { path = "master/ui/widgets.lua", size_bytes = 7637, hash = "24de9664", required_for={"MASTER"}},
    { path = "master/ui_controller.lua", size_bytes = 24135, hash = "bbaaac14", required_for={"MASTER"}},
    { path = "master/ui_diagnostics.lua", size_bytes = 830, hash = "d2a9d0fb", required_for={"MASTER"}},
    },
    rt = {
    { path = "adapters/reactor.lua", size_bytes = 18666, hash = "ae0b468e", required_for={"RT"}},
    { path = "adapters/turbine.lua", size_bytes = 3871, hash = "a9e924f3", required_for={"RT"}},
    { path = "core/control_rails.lua", size_bytes = 8017, hash = "01c1a770", required_for={"RT"}},
    { path = "core/fluid.lua", size_bytes = 5017, hash = "9a5c0bea", required_for={"RT"}},
    { path = "core/turbine_ctrl.lua", size_bytes = 2663, hash = "d1b27731", required_for={"RT"}},
    { path = "core/turbine_regulator.lua", size_bytes = 17134, hash = "50ce7402", required_for={"RT"}},
    { path = "nodes/rt/binding.lua", size_bytes = 3470, hash = "0406bc48", required_for={"RT"}},
    { path = "nodes/rt/command_handler.lua", size_bytes = 10778, hash = "0b4a64a7", required_for={"RT"}},
    { path = "nodes/rt/config.lua", size_bytes = 3611, hash = "809c029c", required_for={"RT"}},
    { path = "nodes/rt/config_normalizer.lua", size_bytes = 23317, hash = "2c2c0f7c", required_for={"RT"}},
    { path = "nodes/rt/discovery_log.lua", size_bytes = 1080, hash = "7d9ceb62", required_for={"RT"}},
    { path = "nodes/rt/discovery_runtime.lua", size_bytes = 9137, hash = "31ad3d94", required_for={"RT"}},
    { path = "nodes/rt/flow_apply_helpers.lua", size_bytes = 10746, hash = "6664e2ce", required_for={"RT"}},
    { path = "nodes/rt/health_payload.lua", size_bytes = 2723, hash = "7a3f83b2", required_for={"RT"}},
    { path = "nodes/rt/main.lua", size_bytes = 97841, hash = "8d587963", required_for={"RT"}},
    { path = "nodes/rt/module_lifecycle.lua", size_bytes = 27375, hash = "fa733934", required_for={"RT"}},
    { path = "nodes/rt/monitor_ui.lua", size_bytes = 25142, hash = "9603b984", required_for={"RT"}},
    { path = "nodes/rt/reactor_steam_guard.lua", size_bytes = 2613, hash = "2f2fa78c", required_for={"RT"}},
    { path = "nodes/rt/startup_diagnostics.lua", size_bytes = 2613, hash = "e5d63978", required_for={"RT"}},
    { path = "nodes/rt/state_handlers.lua", size_bytes = 8762, hash = "aa2155db", required_for={"RT"}},
    { path = "nodes/rt/status_snapshot.lua", size_bytes = 11470, hash = "c5af0558", required_for={"RT"}},
    },
    energy = {
    { path = "adapters/energy_storage.lua", size_bytes = 3648, hash = "fd2dc2e5", required_for={"ENERGY"}},
    { path = "adapters/induction_matrix.lua", size_bytes = 15124, hash = "c3006e4d", required_for={"ENERGY"}},
    { path = "services/matrix_sampling_service.lua", size_bytes = 867, hash = "fff32232", required_for={"ENERGY"}},
    { path = "nodes/energy/command_handler.lua", size_bytes = 1329, hash = "e6b074ac", required_for={"ENERGY"}},
    { path = "nodes/energy/config.lua", size_bytes = 6714, hash = "5a060977", required_for={"ENERGY"}},
    { path = "nodes/energy/config_normalizer.lua", size_bytes = 6260, hash = "0f3e5f0e", required_for={"ENERGY"}},
    { path = "nodes/energy/discovery_log.lua", size_bytes = 2433, hash = "4f723e27", required_for={"ENERGY"}},
    { path = "nodes/energy/discovery_runtime.lua", size_bytes = 17168, hash = "4d225311", required_for={"ENERGY"}},
    { path = "nodes/energy/main.lua", size_bytes = 24660, hash = "a895d5a6", required_for={"ENERGY"}},
    { path = "nodes/energy/matrix_snapshot_runtime.lua", size_bytes = 17943, hash = "9b8b5405", required_for={"ENERGY"}},
    { path = "nodes/energy/matrix_topology_cache.lua", size_bytes = 2052, hash = "54dc9081", required_for={"ENERGY"}},
    { path = "nodes/energy/runtime_context.lua", size_bytes = 2098, hash = "c352f2d4", required_for={"ENERGY"}},
    { path = "nodes/energy/status_payload.lua", size_bytes = 8610, hash = "c0c86b1f", required_for={"ENERGY"}},
    { path = "nodes/energy/storage_snapshot_runtime.lua", size_bytes = 3479, hash = "52992366", required_for={"ENERGY"}},
    { path = "nodes/energy/ui_model.lua", size_bytes = 6005, hash = "faa185db", required_for={"ENERGY"}},
    { path = "nodes/energy/ui_pages.lua", size_bytes = 8317, hash = "056a840d", required_for={"ENERGY"}},
    },
    water = {
    { path = "nodes/water/config.lua", size_bytes = 3793, hash = "3b282920", required_for={"WATER"}},
    { path = "nodes/water/config_normalizer.lua", size_bytes = 989, hash = "09141fba", required_for={"WATER"}},
    { path = "nodes/water/main.lua", size_bytes = 18322, hash = "0c1cd239", required_for={"WATER"}},
    { path = "nodes/water/role_descriptor.lua", size_bytes = 152, hash = "c76ee5e7", required_for={"WATER"}},
    },
    fuel = {
    { path = "nodes/fuel/config.lua", size_bytes = 5586, hash = "48c5be2b", required_for={"FUEL"}},
    { path = "nodes/fuel/config_normalizer.lua", size_bytes = 3722, hash = "40524d32", required_for={"FUEL"}},
    { path = "nodes/fuel/main.lua", size_bytes = 20760, hash = "cb729ee4", required_for={"FUEL"}},
    { path = "nodes/fuel/role_descriptor.lua", size_bytes = 147, hash = "1b38a051", required_for={"FUEL"}},
    { path = "nodes/fuel/logistics_router.lua", size_bytes = 16803, hash = "28477abd", required_for={"FUEL","REPROCESSING"}},
    { path = "nodes/fuel/redstone_router.lua", size_bytes = 8006, hash = "b9ce5b6d", required_for={"FUEL","REPROCESSING"}},
    { path = "nodes/fuel/router_ui.lua", size_bytes = 10358, hash = "f0d6523e", required_for={"FUEL","REPROCESSING"}},
    },
    reprocessing = {
    { path = "nodes/reprocessor/config.lua", size_bytes = 4129, hash = "d5e5ee02", required_for={"REPROCESSING"}},
    { path = "nodes/reprocessor/config_normalizer.lua", size_bytes = 1766, hash = "c45bd644", required_for={"REPROCESSING"}},
    { path = "nodes/reprocessor/main.lua", size_bytes = 20739, hash = "62878552", required_for={"REPROCESSING"}},
    { path = "nodes/reprocessor/role_descriptor.lua", size_bytes = 177, hash = "3a1d8dc9", required_for={"REPROCESSING"}},
    },
    log = {
    { path = "nodes/log_collector/main.lua", size_bytes = 29617, hash = "69befec0", required_for={"LOG"}},
    },
    shared_support = {
    { path = "nodes/support/command_handler.lua", size_bytes = 4590, hash = "568a2b45", required_for={"WATER", "FUEL", "REPROCESSING"}},
    { path = "nodes/support/discovery.lua", size_bytes = 1343, hash = "e8aa30c3", required_for={"WATER", "FUEL", "REPROCESSING"}},
    { path = "nodes/support/role_logic.lua", size_bytes = 571, hash = "a3d15a39", required_for={"ENERGY", "WATER", "FUEL", "REPROCESSING"}},
    { path = "nodes/support/runtime.lua", size_bytes = 3819, hash = "86032e94", required_for={"WATER", "FUEL", "REPROCESSING"}},
    { path = "nodes/support/ui_pages.lua", size_bytes = 5097, hash = "e9f1a7c9", required_for={"WATER", "FUEL", "REPROCESSING", "ENERGY", "RT", "MASTER"}},
    },
  },

  dev_files = {},
}
